// Generated by CoffeeScript 1.8.0
(function() {
  var Abstract, DownCourse, GetCourse, async, checkPage, cheerio, fs, inlineCss, makeNote, noteStore, request, t,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  request = require("request");

  async = require("async");

  fs = require("fs");

  cheerio = require("cheerio");

  inlineCss = require('inline-css');

  noteStore = require('./noteStore');

  makeNote = require("./makeNote");

  DownCourse = (function() {
    function DownCourse(courseUrl) {
      this.courseUrl = courseUrl;
      this.courseName = 'ninghao';
      this.href = [];
      this.content = '';
    }

    DownCourse.prototype.getCourseList = function(cb) {
      var self;
      self = this;
      return request.get(self.courseUrl, function(err, res, body) {
        var $, link, linkLen;
        if (err) {
          return cb(err);
        }
        $ = cheerio.load(body);
        if ($(".course-info h1").length === 0) {
          cb("没有找到课程名，使用默认课程名 " + self.courseName);
        } else {
          self.courseName = $(".course-info h1").text();
          console.log("找到课程名 " + self.courseName);
        }
        link = $("tr > td a");
        linkLen = link.length;
        console.log("查找到得课程列表： " + linkLen);
        if (!linkLen) {
          return cb("奇怪怎么没有找到课程列表？");
        }
        link.each(function(idx, element) {
          return self.href.push($(element).attr("href"));
        });
        if (!self.href.length) {
          return cb("奇怪，应该不会出现这情况吧, @href 为空？");
        }
        console.log("### 获取课程列表 end ###");
        if (!fs.existsSync(self.courseName)) {
          fs.mkdirSync(self.courseName);
        }
        return cb();
      });
    };

    DownCourse.prototype.getAbstract = function(cb) {
      var self;
      self = this;
      return async.eachSeries(self.href, function(item, callback) {
        return request.get('http://ninghao.net' + item, function(err, res, body) {
          var $, $pTag, $title, i, p, _i, _len;
          if (err) {
            return cb("get href error: " + item);
          }
          $ = cheerio.load(body);
          $title = $("#sidebar section div.box strong a");
          $pTag = $(".tab-content section .view-content > div p");
          if ($title.length === 0) {
            return callback("get href no title:" + item);
          }
          if ($pTag.length === 0) {
            return callback("get href no content: " + item);
          }
          self.content += $title.text() + '\n\n';
          for (i = _i = 0, _len = $pTag.length; _i < _len; i = ++_i) {
            p = $pTag[i];
            self.content += $(p).text() + '\n';
            if (i === $pTag.length - 1) {
              self.content += '\n\n';
            }
          }
          console.log(self.content);
          console.log('\n\n');
          console.log("### href text get ok " + item + " ###");
          return callback();
        });
      }, function(eachErr) {
        var write;
        if (eachErr) {
          return cb(eachErr);
        }
        write = fs.createWriteStream(self.courseName + '/' + self.courseName + ".txt");
        write.write(self.content);
        console.log("### " + self.courseName + " all do ###");
        return cb();
      });
    };

    return DownCourse;

  })();

  GetCourse = (function() {
    function GetCourse(starUrl) {
      this.starUrl = starUrl != null ? starUrl : 'http://ninghao.net/course';
    }

    GetCourse.prototype.getCourseUrl = function(cb) {
      return request.get(this.starUrl, function(err, res, body) {
        var $, courseArr;
        if (err) {
          return cb(err);
        }
        $ = cheerio.load(body);
        courseArr = $(".course-list .span4 > a");
        if (!courseArr.length) {
          return cb("getCourseUrl没有发现链接");
        }
        return cb(null, courseArr);
      });
    };

    GetCourse.prototype.tryDown = function(courseArr, cb) {
      return async.eachSeries(courseArr, function(item, callback) {
        var down, url;
        url = 'http://ninghao.net' + item.attribs.href;
        console.log("tryDown url =>", url);
        down = new DownCourse(url);
        return down.getCourseList(function(err) {
          if (err) {
            return callback(err);
          }
          return down.getAbstract(function(err2) {
            if (err2) {
              return callback(err2);
            }
            return callback();
          });
        });
      }, function(eachErr) {
        if (eachErr) {
          return cb(eachErr);
        }
        return console.log("### all page do ###");
      });
    };

    return GetCourse;

  })();

  checkPage = (function(_super) {
    __extends(checkPage, _super);

    function checkPage(startUrl) {
      this.startUrl = startUrl != null ? startUrl : 'http://ninghao.net/course';
      this.nextUrl = [];
      this.nextUrl.push(this.startUrl);
      checkPage.__super__.constructor.apply(this, arguments);
    }

    checkPage.prototype.getPageUrl = function(cb) {
      var self;
      self = this;
      return request.get(this.startUrl, function(err, res, body) {
        var $, nextUrl;
        if (err) {
          return cb(err);
        }
        $ = cheerio.load(body);
        nextUrl = $("li.next a").attr('href');
        if (nextUrl) {
          nextUrl = 'http://ninghao.net' + nextUrl;
          self.nextUrl.push(nextUrl);
          self.startUrl = nextUrl;
          return self.getPageUrl(cb);
        } else {
          return cb();
        }
      });
    };

    return checkPage;

  })(GetCourse);

  Abstract = (function() {
    function Abstract(url) {
      this.url = url;
      this.urlList = [];
      this.content = "";
      this.courseTitle;
    }

    Abstract.prototype.getCourseUrl = function(cb) {
      var self;
      self = this;
      return request.get(self.url, function(err, res, body) {
        var $, i, title, tmp, urlList, _i, _len;
        if (err) {
          return console.log(err);
        }
        $ = cheerio.load(body);
        $("div.section").remove();
        title = $(".course-info h1");
        if (!title.length) {
          return cb("not find title");
        }
        self.courseTitle = title.text();
        urlList = $(".item .content .header a");
        if (!urlList.length) {
          return cb("not find url list");
        }
        for (_i = 0, _len = urlList.length; _i < _len; _i++) {
          i = urlList[_i];
          tmp = {};
          tmp.title = $(i).text();
          tmp.url = "http://ninghao.net" + $(i).attr("href");
          self.urlList.push(tmp);
        }
        console.log("课程:", self.title);
        console.log("数量", self.urlList.length);
        return cb();
      });
    };

    Abstract.prototype.getAbstract = function(data, cb) {
      var self;
      console.log("get ", data.url, data.title);
      self = this;
      return async.waterfall([
        function(callback) {
          return request.get(data.url, function(err, res, body) {
            var $, text;
            if (err) {
              return console.log(err);
            }
            $ = cheerio.load(body);
            text = $("#info");
            if (!text.length) {
              return cb("not find text", data.url, data.title);
            }
            return callback(null, body);
          });
        }, function(body, callback) {
          return inlineCss(body, {
            url: '/'
          }, function(err, html) {
            if (err) {
              return console.log(err);
            }
            return callback(null, html);
          });
        }, function(html, callback) {
          var $, text;
          $ = cheerio.load(html);
          text = $("#info").html();
          self.content += "<h3>" + data.title + "</h3><br/><br/>";
          self.content += "" + text + "<br/></br/>";
          return cb();
        }
      ]);
    };

    Abstract.prototype.getContent = function(cb) {
      var self;
      self = this;
      return async.eachSeries(self.urlList, function(item, callback) {
        return self.getAbstract(item, callback);
      }, function(err) {
        var $, write;
        if (err) {
          return console.log(err);
        }
        $ = cheerio.load(self.content);
        self.content = $.html({
          xmlMode: true,
          decodeEntities: true
        });
        write = fs.createWriteStream(self.courseTitle + ".txt");
        write.write(self.content);
        return cb();
      });
    };

    Abstract.prototype.createNote = function(cb) {
      var self;
      self = this;
      return makeNote(noteStore, self.courseTitle, self.content, {}, function(err) {
        if (err) {
          return console.log(err);
        }
        console.log("create ok");
        return cb();
      });
    };

    Abstract.prototype.pushNote = function(cb) {
      var self;
      self = this;
      return async.waterfall([
        function(callback) {
          return self.getCourseUrl(callback);
        }, function(callback) {
          return self.getContent(callback);
        }, function(callback) {
          return self.createNote(callback);
        }
      ]);
    };

    return Abstract;

  })();

  t = new Abstract("http://ninghao.net/course/1444");

  t.pushNote();

}).call(this);

//# sourceMappingURL=app.js.map
