// Generated by CoffeeScript 1.8.0
(function() {
  var DownCourse, GetCourse, async, cheerio, down, fs, request;

  request = require("request");

  async = require("async");

  fs = require("fs");

  cheerio = require("cheerio");

  DownCourse = (function() {
    function DownCourse(courseUrl) {
      this.courseUrl = courseUrl;
      this.courseName = 'ninghao';
      this.href = [];
      this.content = '';
    }

    DownCourse.prototype.getCourseList = function(cb) {
      var self;
      self = this;
      return request.get(self.courseUrl, function(err, res, body) {
        var $, link, linkLen;
        if (err) {
          return cb(err);
        }
        $ = cheerio.load(body);
        if ($(".course-info h1").length === 0) {
          cb("没有找到课程名，使用默认课程名 " + self.courseName);
        } else {
          self.courseName = $(".course-info h1").text();
          console.log("找到课程名 " + self.courseName);
        }
        link = $("tr > td a");
        linkLen = link.length;
        console.log("查找到得课程列表： " + linkLen);
        if (!linkLen) {
          return cb("奇怪怎么没有找到课程列表？");
        }
        link.each(function(idx, element) {
          return self.href.push($(element).attr("href"));
        });
        if (!self.href.length) {
          return cb("奇怪，应该不会出现这情况吧, @href 为空？");
        }
        console.log("### 获取课程列表 end ###");
        if (!fs.existsSync(self.courseName)) {
          fs.mkdirSync(self.courseName);
        }
        return cb();
      });
    };

    DownCourse.prototype.getAbstract = function(cb) {
      var self;
      self = this;
      return async.eachSeries(self.href, function(item, callback) {
        return request.get('http://ninghao.net' + item, function(err, res, body) {
          var $, $pTag, $title, i, p, _i, _len;
          if (err) {
            return cb("get href error: " + item);
          }
          $ = cheerio.load(body);
          $title = $("#sidebar section div.box strong a");
          $pTag = $(".tab-content section .view-content > div p");
          if ($title.length === 0) {
            return callback("get href no title:" + item);
          }
          if ($pTag.length === 0) {
            return callback("get href no content: " + item);
          }
          self.content += $title.text() + '\n\n';
          for (i = _i = 0, _len = $pTag.length; _i < _len; i = ++_i) {
            p = $pTag[i];
            self.content += $(p).text() + '\n';
            if (i === $pTag.length - 1) {
              self.content += '\n\n';
            }
          }
          console.log(self.content);
          console.log('\n\n');
          console.log("### href text get ok " + item + " ###");
          return callback();
        });
      }, function(eachErr) {
        var write;
        if (eachErr) {
          return cb(eachErr);
        }
        write = fs.createWriteStream(self.courseName + '/' + self.courseName + ".txt");
        write.write(self.content);
        console.log("### " + self.courseName + " all do ###");
        return cb();
      });
    };

    return DownCourse;

  })();

  down = new DownCourse('http://ninghao.net/course/2000');

  async.series([
    function(cb) {
      return down.getCourseList(cb);
    }, function(cb) {
      return down.getAbstract(cb);
    }
  ]);

  GetCourse = (function() {
    function GetCourse(starUrl) {
      this.starUrl = starUrl != null ? starUrl : 'http://ninghao.net/course';
    }

    GetCourse.prototype.getCourseUrl = function(cb) {
      return request.get(this.starUrl, function(err, res, body) {
        var $, courseArr;
        if (err) {
          return cb(err);
        }
        $ = cheerio.load(body);
        courseArr = $(".course-list .span4 > a");
        if (!courseArr.length) {
          return cb("getCourseUrl没有发现链接");
        }
        return cb(null, courseArr);
      });
    };

    GetCourse.prototype.tryDown = function(courseArr, cb) {
      return async.eachSeries(courseArr, function(item, callback) {
        var $, url;
        $ = cheerio.load(item);
        url = $("a").href;
        console.log("tryDown url =>", url);
        return down = new ninghao(url);
      });
    };

    return GetCourse;

  })();

}).call(this);

//# sourceMappingURL=app.js.map
