// Generated by CoffeeScript 1.8.0
(function() {
  var mailOptions, nodemailer, smtpTransport, transport;

  nodemailer = require('nodemailer');

  smtpTransport = require('nodemailer-smtp-transport');

  transport = nodemailer.createTransport(smtpTransport({
    host: 'smtp.exmail.qq.com',
    port: 465,
    secure: true,
    auth: {
      user: process.env.EMAIL_NAME,
      pass: process.env.EMAIL_PWD
    }
  }));

  mailOptions = {
    from: 'yuankui@mykar.com',
    to: 'youqingkui@qq.com',
    subject: 'hi',
    text: 'hello',
    attachments: {
      filename: 'app.js',
      path: 'app.js'
    }
  };

  transport.sendMail(mailOptions, function(err, info) {
    if (err) {
      return console.log(err);
    }
    return console.log(info);
  });

}).call(this);

//# sourceMappingURL=email.js.map
