// Generated by CoffeeScript 1.8.0
(function() {
  var mailOptions, nodemailer, smtpTransport, transport;

  nodemailer = require('nodemailer');

  smtpTransport = require('nodemailer-smtp-transport');

  transport = nodemailer.createTransport({
    service: 'QQex',
    auth: {
      user: process.env.EMAIL_NAME,
      pass: process.env.EMAIL_PWD
    }
  });

  mailOptions = {
    from: 'yuankui@mykar.com',
    to: 'youqingkui_3@kindle.cn',
    subject: 'hi',
    text: 'hello',
    attachments: {
      filename: 'sass教程.txt',
      path: 'app.js'
    }
  };

  transport.sendMail(mailOptions, function(err, info) {
    if (err) {
      return console.log(err);
    }
    return console.log(info);
  });

}).call(this);

//# sourceMappingURL=email.js.map
