// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, makeNote;

  Evernote = require('evernote').Evernote;

  makeNote = function(noteStore, noteTitle, noteBody, options, callback) {
    var attr, nBody, ourNote;
    nBody = '<?xml version="1.0" encoding="UTF-8"?>';
    nBody += '<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">';
    nBody += '<en-note>' + noteBody + '</en-note>';
    console.log(nBody);
    ourNote = new Evernote.Note;
    ourNote.title = noteTitle;
    ourNote.content = nBody;
    if (options) {
      attr = new Evernote.NoteAttributes;
      if (options.notebookGuid) {
        ourNote.notebookGuid = options.notebookGuid;
      }
      if (options.tagNames) {
        ourNote.tagNames = options.tagNames;
      }
      if (options.sourceURL) {
        attr.sourceURL = options.sourceURL;
      }
      if (options.resources) {
        ourNote.resources = options.resources;
      }
      ourNote.attributes = attr;
    }
    noteStore.createNote(ourNote, function(err, note) {
      if (err) {
        console.log(callback(err));
      } else {
        callback(null, note);
      }
    });
  };

  module.exports = makeNote;

}).call(this);

//# sourceMappingURL=makeNote.js.map
